<?php

/**
 * @file
 * Contains github_repo.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_help().
 */
function github_repo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the github_repo module.
    case 'help.page.github_repo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides github_repo entity as an example of creating custom entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Impelments hook_entity_base_field_info().
 */
function github_repo_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() == 'user') {
    // Add the Pfizer Login Employee Type field.
    $fields['github_repo_github_user_name']  = BaseFieldDefinition::create('string')
      ->setLabel(t('Github username.'))
      ->setDescription(t('Username on Github.'))
      ->setSettings(array(
        'max_length' => 255,
        'text_processing' => 0,
      ))
      ->setDefaultValue('')
      ->setDisplayOptions('view', array(
        'label' => 'above',
        'type' => 'string',
        'weight' => -4,
      ))
      ->setDisplayOptions('form', array(
        'type' => 'string_textfield',
        'weight' => -4,
      ))
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }

  return $fields;
}
